# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68be8be83fbf5ed4449ea5be7e0d0d8474ac101673623ac9e04fd6cfc4b070b69fd1551aae4610187dc7936720c772ca0645f2509df416fac9578fc44689ae69

test:
  secret_key_base: ad51ef60609ad80909decef0a2325304e3ca636926c99290a3cf95204269a049b4e2b1ffb9f76adae04840d04ca2ed11c0acbab2a5d183004dc393ee3678483e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
